CarsExample/Models/Car.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace StorageExample.Models
{
    public class Car
    {
        public int CarId { get; set; }
        [Required, Index("UX_Car_VIN", IsUnique = true)]
        [StringLength(17, MinimumLength = 17)]
        public string VIN { get; set; }
        public decimal Price { get; set; }
        public int Mileage { get; set; }
        public int MaxSpeed { get; set; }
        public Guid Photo { get; set; }
        
        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }

        [Required, Display(Name = "Car model")]
        public int CarModelId { get; set; }
        
        public virtual CarModel CarModel { get; set; } 
    }
}

CarsExample/Controllers/CarController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.Collections.Generic;
using System.Data;
using System.Linq.Dynamic;
using System.Net;
using System.Web;
using StorageExample.Models;
using StorageExample.DataAccess;
using StorageExample.Helpers;
using System.IO;
using System.Diagnostics;
using System.Linq.Expressions;
using StorageExample.FileSystem;
using CarsExample.Helpers;

namespace StorageExample.Controllers
{
    public class CarController : Controller
    {
        private static readonly Dictionary<string, Expression<Func<Car, object>>> _carExpressions;

        static CarController()
        {
            _carExpressions = new Dictionary<string, Expression<Func<Car, object>>>();
            _carExpressions.Add("Manufacturer", c => c.CarModel.Manufacturer.Name);
            _carExpressions.Add("CarModel", c => c.CarModel.Name);
        }

        private StorageContext db = new StorageContext();

        // GET: /Car/
        public ActionResult Index()
        {
            var cars = db.Cars.Include(c => c.CarModel);

            ViewBag.carModelsList = SelectListHelper.GetCarModelsList();
            return View(cars.ToList());
        }

        // GET: /Car/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // GET: /Car/Create
        public ActionResult Create()
        {
            ViewBag.CarModelId = new SelectList(db.CarModels, "CarModelId", "Name");
            return View();
        }

        // POST: /Car/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Car car)
        {
            if (ModelState.IsValid)
            {
                car.Photo = FileHelper.GetUploadedFileId(Request);
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CarModelId = new SelectList(db.CarModels, "CarModelId", "Name", car.CarModelId);
            return View(car);
        }

        // GET: /Car/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarModelId = new SelectList(db.CarModels, "CarModelId", "Name", car.CarModelId);
            return View(car);
        }

        // POST: /Car/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                car.Photo = FileHelper.GetUploadedFileId(Request);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarModelId = new SelectList(db.CarModels, "CarModelId", "Name", car.CarModelId);
            return View(car);
        }

        // GET: /Car/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: /Car/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Cars.Find(id);
            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult LoadData()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

            sortColumn = !string.IsNullOrEmpty(sortColumn) ? sortColumn : "Price";

            //Paging Size
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;

            // Getting all data
            var carsData = (from c in db.Cars.Include(c => c.CarModel.Manufacturer) select c);

            //Sorting
            if (_carExpressions.ContainsKey(sortColumn))
            {
                if (sortColumnDir != "desc")
                {
                    carsData = carsData.OrderBy(_carExpressions[sortColumn]);
                }
                else
                {
                    carsData = carsData.OrderByDescending(_carExpressions[sortColumn]);
                }
            }
            else
            {
                carsData = carsData.OrderBy(sortColumn + " " + sortColumnDir);
            }
            
            ////Search
            if (!string.IsNullOrEmpty(searchValue))
            {
                carsData = carsData.Where(
                    m => m.CarModel.Manufacturer.Name.Contains(searchValue) || m.CarModel.Name.Contains(searchValue));
            }

            recordsTotal = carsData.Count();
            var data = carsData.Skip(skip).Take(pageSize).Select(
                car => new {
                    CarId = car.CarId,
                    Manufacturer = car.CarModel.Manufacturer.Name,
                    CarModel = car.CarModel.Name,
                    Price = car.Price,
                    Mileage = car.Mileage,
                    MaxSpeed = car.MaxSpeed,
                    VIN = car.VIN,
                    Photo = car.Photo,
                })
                .ToList();

            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CarsExample/Controllers/ImageController.cs
using StorageExample.FileSystem;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StorageExample.Controllers
{
    public class ImageController : Controller
    {
        //
        // GET: /Image/id
        public ActionResult Get(Guid id)
        {
            return new FileContentResult(FileManager.Get(id), "image/jpeg");
        }
	}
}

CarsExample/Views/Car/Create.cshtml
@model StorageExample.Models.Car

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Car", FormMethod.Post,
                                      new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.VIN, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VIN)
                @Html.ValidationMessageFor(model => model.VIN)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mileage, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mileage)
                @Html.ValidationMessageFor(model => model.Mileage)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarModelId, "Car model", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CarModelId, (SelectList)ViewBag.carModelsList)
                @Html.ValidationMessageFor(model => model.CarModelId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoFile, "Choose image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.PhotoFile, new { type = "file" })
                @Html.ValidationMessageFor(x => x.PhotoFile)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


}

CarsExample/Views/Car/Delete.cshtml
@model StorageExample.Models.Car

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarModel.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarModel.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mileage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mileage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CarsExample/Views/Car/Details.cshtml
@model StorageExample.Models.Car

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Car</h4>
	<hr />
    <img src="@Url.Action("Get", "Image", new { id = Model.Photo })" class="item-image">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarModel.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarModel.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mileage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mileage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CarId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CarsExample/Views/Car/Edit.cshtml
@model StorageExample.Models.Car

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Car", FormMethod.Post,
                                      new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.CarId)

        <div class="form-group">
            @Html.LabelFor(model => model.VIN, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VIN)
                @Html.ValidationMessageFor(model => model.VIN)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mileage, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mileage)
                @Html.ValidationMessageFor(model => model.Mileage)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarModelId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CarModelId")
                @Html.ValidationMessageFor(model => model.CarModelId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoFile, "Choose image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.PhotoFile, new { type = "file" })
                @Html.ValidationMessageFor(x => x.PhotoFile)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarsExample/Views/Car/Index.cshtml
@model IEnumerable<StorageExample.Models.Car>

@{
    ViewBag.Title = "Index";
}

@section styles {
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
}

@section scripts{

<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $(document).ready(function () {
        $("#carGrid").DataTable({
            "processing": true,
            "serverSide": true,
            "filter": true,
            "orderMulti": false,
            "order": [[ 1, "asc" ]],
            "pageLength": 4,
            "lengthMenu": [2, 4, 10, 12, 20],
            "oLanguage": {
                "sSearch": "Manufacturer or model:"
            },
            "ajax": {
                "url": "/Car/LoadData",
                "type": "POST",
                "datatype": "json",
            },
            "columnDefs": [
                {
                    "targets": [1, 2],
                    "searchable": true,
                    "orderable": true,
                },
                {
                    "targets": [3],
                    "searchable": false,
                    "orderable": true,
                },
                {
                    "targets": ["_all"],
                    "searchable": false,
                    "orderable": false,
                },
            ],
            "columns": [
                {
                    "name": "PreviewImage",
                    "render": function (data, type, full, meta)
                        { return "<img src='@Url.RouteUrl(new { controller = "Image", action = "Get" })/" + full.Photo + "' class='preview-item-image'>"; }
                },
                { "data": "Manufacturer", "name": "Manufacturer", "autoWidth": true },
                { "data": "CarModel", "name": "CarModel", "autoWidth": true },
                { "data": "Price", "name": "Price", "autoWidth": true },
                { "data": "Mileage", "title": "Mileage", "name": "Mileage", "autoWidth": true },
                { "data": "MaxSpeed", "name": "MaxSpeed", "autoWidth": true },
                { "data": "VIN", "name": "VIN", "autoWidth": true },
                {
                    data: null, render: function (data, type, row) {
                        return "<a href='@Url.RouteUrl(new { controller = "Car", action = "Details" })/" + row.CarId + "'>Details</a> | " + 
                        "<a href='@Url.RouteUrl(new { controller = "Car", action = "Edit" })/" + row.CarId + "'>Edit</a> | " +
                        "<a href='@Url.RouteUrl(new { controller = "Car", action = "Delete" })/" + row.CarId + "'>Delete</a>" 
                    }
                },
            ],
        });
    }); 
</script>
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div style="width:90%; margin:0 auto;">
    <table id="carGrid" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Image</th>
                <th>Manufacturer</th>
                <th>Car model</th>
                <th>Price</th>
                <th>Mileage</th>
                <th>MaxSpeed</th>
                <th>VIN</th>
                <th>Actions</th>
            </tr>
        </thead>
    </table>
</div>